apiVersion: v1beta1
kind: AgentConfig
metadata:
  name: lab
rendezvousIP: 192.168.1.202
additionalNTPSources:
  - 192.168.1.201
hosts:
  - hostname: master1
    role: master
    interfaces:
      - name: enp2s0
        macAddress: 0c:42:a1:55:f3:06
    networkConfig:
      interfaces:
        - name: enp2s0
          type: ethernet
          state: up
          mac-address: 0c:42:a1:55:f3:06
          ipv4:
            enabled: true
            address:
              - ip: 192.168.1.202
                prefix-length: 24
            dhcp: false
      dns-resolver:
        config:
          server:
            - 192.168.1.201
      routes:
        config:
          - destination: 0.0.0.0/0
            next-hop-address: 192.168.1.1
            next-hop-interface: enp2s0
