apiVersion: config.openshift.io/v1
kind: OAuth
metadata:
  name: cluster
spec:
  identityProviders:
  - name: github
    mappingMethod: claim 
    type: GitHub
    github:
      clientID: <your-client-id-here>
      clientSecret: 
        name: github-oauth-secret
      organizations:
      - <your-github-name>
