apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: app-tls
  labels:
    app: <replace-me>
spec:
  host: <replace-me>.keam.org
  to:
    kind: Service
    name: <replace-me>
    weight: 100
  port:
    targetPort: <replace-me>
  tls:
    termination: edge
    externalCertificate:
      name: app-tls-cert-secret
