apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: router-certs
  namespace: openshift-ingress
  labels:
    app: cert-manager
spec:
  secretName: router-certs
  secretTemplate:
    labels:
      app: cert-manager
  duration: 2160h
  renewBefore: 360h
  subject:
    organizations:
      - Keam Org
  commonName: '*.lab.keam.org'
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
    rotationPolicy: Always
  usages:
    - server auth
    - client auth
  dnsNames:
    - '*.lab.keam.org'
    - '*.apps.lab.keam.org'
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
